### PR TITLE
Fix for UE 4.11 and allow using in C++ source code files.

### PR DESCRIPTION
**Pull request by gameDNAstudio**

### CODE REVIEW

**Comment by MarcoWilliamsPF** [comment]
@gameDNAstudio  thanks for your contribution here.  I've reviewed these changes, and I have a couple of issues / questions. 

1.  These changes should not go into nightly.  Nightly is our generated code from Jenkins and will get overwritten by the SDK Generator.

2.  These changes really need to go into the SDK Generator ( which we can do for you ) or you can submit them to the generator.  https://github.com/PlayFab/SDKGenerator

3.  Question:  How does this change effect users that are using 4.9?  We have a user base that still uses for 4.9,  will the project downgrade nicely?  I would rather have a project that is upgradeable to 4.11 with a prompt than to just not work in 4.9.  So we will need to check the backwards compatibility before we can accept this change.

**Comment by gameDNAstudio** [comment]
1. OK
2. Please do it for me
3. These changes shouldn't affect UE 4.9 but I recommend you making separate SDK version for each UE4 version. UE4 versions generally are not compatible between each other and it's normal that plugins for UE4 have separate versions for each engine release.

**Comment by pgilmorepf** [comment]
Thank you for your submission!

I've reviewed it, and I think you've exposed a deeper issue than we anticipated in our system.

As such, I have a proposal for you, and I'd like your feedback:
I am inclined to revise our SdkGenerator to build ALL of our enum types (and not just hard coding Region and Permissions).  I would use the structure you laid out above, except the PlayFabTypes.h
file would probably contain about ten to twenty enums (depending on which sdk you're using).  This will affect a similar number of API-Calls, and any blueprint nodes making those calls.

A bunch of existing parameters on existing apis (and thus blueprint nodes) would end up being converted from FString, to a specific enum type.
1. For existing blueprint nodes, if one of the input parameters changes from string to enum, will this cause work for projects that are in-progress (such as yours).
2. Is this an acceptable amount of work for the improvement of clarifying those inputs?
3. Do you view this as a beneficial change to the SDK?

As we say in the readme, this SDK is in beta right now, and we anticipate needing to make some of these structural changes before we remove the Beta annotation and start releasing official versions.  None-the-less, we hope to minimize the impact of these changes on our customers.

Thanks!

**Comment by gameDNAstudio** [comment]
@pgilmorepf 
1. Yes
2. Yes
3. Yes

**Comment by pgilmorepf** [comment]
Excellent!  I just pushed a change for internal code review which builds unreal-enums for all of our enum types.  I expect that change to be visible in our "nightly" branch very soon (maybe tomorrow), and it'll be published to master next week.  Thank you for finding this!

**Pull request closed without merging**
